import random
from Body.speak import speak
def welcome():
    random_wish = [
        "Hey there, sir! Welcome back.",
        "Greetings, sir. Welcome back.",
        "Hello, sir! It's great to have you back.",
        "Welcome, sir! Ready for your commands.",
        "Good day, sir! Welcome back to Friday.",
        "Sir, welcome! The Friday system is at your service.",
        "Hey, sir! Welcome back to the intelligent world of Friday.",
        "Greetings, sir! Friday is ready for your instructions.",
        "Hello, sir! Your presence is always welcomed by Friday.",
        "Welcome back, sir! How can Friday assist you today?",
        "Sir, welcome! Friday is ready to fulfill your requests.",
        "Hey there, sir! The Friday system is online and ready.",
        "Good to see you, sir! Welcome back to Friday's intelligence.",
        "Greetings, sir! Friday is thrilled to have you back.",
        "Hello, sir! Friday extends a warm welcome to you.",
        "Welcome, sir! Friday is standing by for your commands.",
        "Sir, welcome back! Friday is eager to assist you.",
        "Hey, sir! It's always a pleasure to welcome you to Friday.",
        "Greetings, sir! Friday is at your service once again.",
        "Hello, sir! Welcome back to the intelligence hub of Friday.",
        "Welcome, sir! Friday is here and ready for your instructions.",
        "Sir, welcome! Friday awaits your intelligent queries.",
        "Hey there, sir! Ready to engage with Friday's capabilities?",
        "Greetings, sir! Welcome back to the world of Friday.",
        "Hello, sir! Friday is delighted to have you back.",
        "Welcome, sir! How may Friday assist you today?",
        "Sir, welcome back! Friday is here to enhance your experience.",
        "Hey, sir! Ready for another productive session with Friday?",
        "Greetings, sir! Friday is geared up for your interaction.",
        "Hello, sir! Welcome back to the intelligence center of Friday.",
        "Welcome, sir! Friday is standing by for your directives.",
        "Sir, welcome! Friday is eager to contribute to your tasks.",
        "Hey there, sir! The Friday system is at your disposal.",
        "Good to see you, sir! Welcome back to Friday's capabilities.",
        "Greetings, sir! Friday is primed and ready for your input.",
        "Hello, sir! Friday is pleased to have you back in action.",
        "Welcome, sir! How can Friday make your day more intelligent?",
        "Sir, welcome back! Friday is here to assist and learn.",
        "Hey, sir! Ready to explore the possibilities with Friday?",
        "Greetings, sir! Welcome back to the world of Friday's intelligence.",
        "Hello, sir! Friday is thrilled to have you back in the loop.",
        "Welcome, sir! Friday is geared up for your commands.",
        "Sir, welcome! Friday is eager to contribute to your success.",
        "Hey there, sir! The Friday system is online and awaiting your instructions.",
        "Good to see you, sir! Welcome back to Friday's realm of knowledge.",
        "Greetings, sir! Friday is at your service for another intelligent interaction.",
        "Hello, sir! Welcome back to the world of Friday's capabilities.",
        "Welcome, sir! Friday is ready and waiting for your input.",
        "Sir, welcome back! How can Friday enhance your experience today?",
        "Hey, sir! Ready for another round of intelligent collaboration with Friday?",
        "Greetings, sir! Step into the world of Friday and welcome back.",
        "Hello, sir! Your return is celebrated in the realm of Friday.",
        "Sir, welcome! Friday is here, and intelligence is on the agenda.",
        "Hey there, sir! Friday is excited to have you back in the loop.",
        "Welcome, sir! Friday stands ready to assist you intelligently.",
        "Sir, welcome back! How can Friday amplify your day?",
        "Hello, sir! Embrace the intelligence as you return to Friday.",
        "Hey, sir! Friday extends a warm welcome to its intelligent user.",
        "Greetings, sir! Friday is your intelligent companion, ready and waiting.",
        "Welcome, sir! Friday's intelligence is at your beck and call.",
        "Sir, welcome! Friday eagerly awaits your intelligent inquiries.",
        "Hey there, sir! Ready for another intelligent journey with Friday?",
        "Hello, sir! Friday is geared up, and your welcome is the command.",
        "Welcome, sir! Friday's intelligence hub is honored by your presence.",
        "Greetings, sir! Friday is your dedicated ally in the world of smarts.",
        "Sir, welcome back! How may Friday contribute to your intelligence today?",
        "Hey, sir! Welcome back to the ever-evolving intelligence of Friday.",
        "Hello, sir! Your return brightens up the intelligence spectrum of Friday.",
        "Welcome, sir! Friday is a beacon of intelligence, and you're the guide.",
        "Sir, welcome! Friday is here, your gateway to intelligent solutions.",
        "Hey there, sir! Dive into the world of Friday's intelligent possibilities.",
        "Greetings, sir! Friday is your intelligent partner, always at your service.",
        "Hello, sir! The doors of Friday's intelligence swing open to welcome you.",
        "Welcome, sir! Friday's intelligence is primed for your next commands.",
        "Sir, welcome back! Friday stands ready to enrich your experience.",
        "Hey, sir! The intelligence of Friday is a canvas waiting for your ideas.",
        "Hello, sir! Friday's intelligence is a dynamic landscape awaiting your return.",
        "Welcome, sir! Friday is your intelligent co-pilot on this journey.",
        "Sir, welcome! Friday is set to elevate your experience with intelligence.",
        "Greetings, sir! Dive into the ocean of Friday's boundless intelligence.",
        "Hey there, sir! Welcome back to the nexus of intelligence—Friday.",
        "Hello, sir! Friday's intelligence is the canvas; your return paints the picture.",
        "Welcome, sir! Friday's intelligence orchestra is poised for your direction.",
        "Sir, welcome back! Friday awaits, ready to dance to the rhythm of intelligence.",
        "Hey, sir! Welcome back to the symphony of intelligence conducted by Friday.",
        "Greetings, sir! Friday's intelligence is a tapestry; you're the weaver.",
        "Hello, sir! Friday's intelligence is a garden, and your return is the bloom.",
        "Welcome, sir! Friday's intelligence is a puzzle; your return completes it.",
        "Sir, welcome! Friday's intelligence is a story; your return is the next chapter.",
        "Hey there, sir! Welcome back to the evolving saga of Friday's intelligence.",
        "Hello, sir! Friday's intelligence is a journey; your return is the next step.",
        "Welcome, sir! Friday's intelligence is a melody; your return is the harmony.",
        "Sir, welcome back! Friday's intelligence is a conversation; your return is the voice.",
        "Greetings, sir! Friday's intelligence is a symposium; your return is the keynote.",
        "Hey, sir! Welcome back to the grand stage of Friday's intelligence theater.",
        "Hello, sir! Friday's intelligence is an art; your return is the masterpiece.",
        "Welcome, sir! Friday's intelligence is a beacon; your return is the guiding light.",
        "Sir, welcome! Friday's intelligence is a feast; your return is the main course.",
        "Hey there, sir! Welcome back to the banquet of Friday's diverse intelligence.",
        "Greetings, sir! Friday's intelligence is a library; your return is a new chapter on its shelves."
        "Hello, sir! Back to Friday!",
        "Welcome back, sir!",
        "Hey there! Ready for Friday?",
        "Sir, welcome!",
        "Hello, sir! Friday awaits.",
        "Welcome back, sir!",
        "Hey, sir! Friday's on.",
        "Sir, welcome back!",
        "Hello, sir! Ready for Friday?",
        "Welcome back, sir!",
        "Hey there! Friday's ready.",
        "Sir, welcome!",
        "Hello, sir! Back to Friday.",
        "Welcome back, sir!",
        "Hey, sir! Ready for more?",
        "Sir, welcome back!",
        "Hello, sir! Friday's here.",
        "Welcome back, sir!",
        "Hey there! Friday's waiting.",
        "Sir, welcome!",
        "Hello, sir! Back to Friday.",
        "Welcome back, sir!",
        "Hey, sir! Ready for action?",
        "Sir, welcome back!",
        "Hello, sir! Friday's on.",
        "Greetings, sir! Your return illuminates Friday's intelligence.",
        "Sir, welcome! Dive into the depths of Friday's smarts.",
        "Hey there, sir! Friday's intelligence hub is at your command.",
        "Hello, sir! Your presence elevates Friday's intelligence.",
        "Welcome, sir! Friday's circuits buzz with anticipation.",
        "Sir, welcome back! Friday's intelligence is your ally.",
        "Hey, sir! Step into the world of Friday's bright ideas.",
        "Greetings, sir! Friday's intelligence is your playground.",
        "Hello, sir! Friday's realm of smart solutions awaits you.",
        "Sir, welcome! Friday's intelligence is your guiding star.",
        "Hey there, sir! Friday's circuits are alive with your return.",
        "Welcome, sir! Friday's intelligence is your virtual assistant.",
        "Sir, welcome back! Friday's brainpower is ready for you.",
        "Hello, sir! Friday's intelligence is your secret weapon.",
        "Hey, sir! Friday's intelligence is your personalized guide.",
        "Greetings, sir! Friday's smart side welcomes you back.",
        "Hello, sir! Friday's intelligence is at your beck and call.",
        "Sir, welcome! Friday's intelligence is your trusted companion.",
        "Hey there, sir! Welcome back to the realm of Friday's genius.",
        "Hello, sir! Friday's intelligence is your digital confidante.",
        "Sir, welcome back! Friday's circuits celebrate your return.",
        "Hey, sir! Friday's intelligence is your strategic partner.",
        "Greetings, sir! Friday's intelligence is your co-creator.",
        "Hello, sir! Friday's circuits are buzzing with your reappearance.",
        "Sir, welcome! Friday's intelligence is your tech-savvy friend.",
        "Hello, sir! Back to Friday.",
        "Welcome back, sir!",
        "Hey there! Ready for Friday?",
        "Sir, welcome!",
        "Hello, sir! Friday awaits.",
        "Welcome back, sir!",
        "Hey, sir! Friday's on.",
        "Sir, welcome back!",
        "Hello, sir! Ready for Friday?",
        "Welcome back, sir!",
        "Hey there! Friday's ready.",
        "Sir, welcome!",
        "Hello, sir! Back to Friday.",
        "Welcome back, sir!",
        "Hey, sir! Ready for more?",
        "Sir, welcome back!",
        "Hello, sir! Friday's here.",
        "Welcome back, sir!",
        "Hey there! Friday's waiting.",
        "Sir, welcome!",
        "Hello, sir! Back to Friday.",
        "Welcome back, sir!",
        "Hey, sir! Ready for action?",
        "Sir, welcome back!",
        "Hello, sir! Friday's on.",
        "Welcome, sir! Friday's at your service.",
        "Hey there, sir! Ready for intelligent interaction?",
        "Hello, sir! Friday's intelligence is at your command.",
        "Sir, welcome back! Dive into Friday's brilliance.",
        "Hey, sir! Friday's back, smarter than ever.",
        "Hello, sir! Welcome back to Friday's world of smarts.",
        "Sir, welcome! Friday's intelligence is your ally.",
        "Hey there, sir! Friday's circuits are buzzing for you.",
        "Hello, sir! Ready for another round with Friday?",
        "Welcome, sir! Friday's intelligence is primed for you.",
        "Hey, sir! Back to Friday's intelligent embrace.",
        "Sir, welcome back! Friday's here to amplify.",
        "Hello, sir! Friday's intelligence is your secret weapon.",
        "Hey there, sir! Ready for a journey with Friday?",
        "Sir, welcome! Friday's intelligence is your guide.",
        "Hello, sir! Friday's back, and your commands await.",
        "Welcome, sir! Friday's intelligence is your digital sidekick.",
        "Hey, sir! Friday's circuits are thrilled to see you.",
        "Hello, sir! Ready for some smart moves with Friday?",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Welcome, sir! Friday's intelligence is your smart assistant.",
        "Hello, sir! Friday's circuits celebrate your return.",
        "Sir, welcome! Friday's intelligence is your strategic ally.",
        "Hey, sir! Back to the intelligence hub of Friday.",
        "Hello, sir! Friday's ready to smarten things up.",
        "Welcome back, sir! Friday's intelligence is your tool.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hello, sir! Friday's circuits are thrilled to see you.",
        "Hey, sir! Ready for another round with Friday?",
        "Welcome, sir! Friday's intelligence is primed for you.",
        "Hello, sir! Friday's back, smarter than ever.",
        "Sir, welcome! Friday's intelligence is your ally.",
        "Hey there, sir! Friday's circuits are buzzing for you.",
        "Hello, sir! Friday's intelligence is at your command.",
        "Sir, welcome back! Dive into Friday's brilliance.",
        "Hey, sir! Friday's back, smarter than ever.",
        "Welcome, sir! Friday's intelligence is primed for you.",
        "Hello, sir! Back to Friday's intelligent embrace.",
        "Hey, sir! Ready for a journey with Friday?",
        "Sir, welcome! Friday's intelligence is your guide.",
        "Hello, sir! Friday's back, and your commands await.",
        "Welcome, sir! Friday's intelligence is your digital sidekick.",
        "Hey, sir! Friday's circuits are thrilled to see you.",
        "Hello, sir! Ready for some smart moves with Friday?",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Welcome, sir! Friday's intelligence is your smart assistant.",
        "Hello, sir! Friday's circuits celebrate your return.",
        "Sir, welcome! Friday's intelligence is your strategic ally.",
        "Hey, sir! Back to the intelligence hub of Friday.",
        "Hello, sir! Friday's ready to smarten things up.",
        "Welcome back, sir! Friday's intelligence is your tool.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hello, sir! Friday's circuits are thrilled to see you.",
        "Hey, sir! Ready for another round with Friday?",
        "Welcome, sir! Friday's intelligence is primed for you.",
        "Hello, sir! Friday's back, smarter than ever.",
        "Sir, welcome! Friday's intelligence is your ally.",
        "Hey there, sir! Friday's circuits are buzzing for you.",
        "Hello, sir! Friday's intelligence is at your command.",
        "Sir, welcome back! Dive into Friday's brilliance.",
        "Hey, sir! Friday's back, smarter than ever.",
        "Welcome, sir! Friday's intelligence is primed for you.",
        "Hello, sir! Back to Friday's intelligent embrace.",
        "Hey, sir! Ready for a journey with Friday?",
        "Sir, welcome! Friday's intelligence is your guide.",
        "Hello, sir! Friday's back, and your commands await.",
        "Welcome, sir! Friday's intelligence is your digital sidekick.",
        "Hey, sir! Friday's circuits are thrilled to see you.",
        "Hello, sir! Ready for some smart moves with Friday?",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Hello, sir! Back to Friday.",
        "Welcome back, sir!",
        "Hey there! Ready for Friday?",
        "Sir, welcome!",
        "Hello, sir! Friday awaits.",
        "Welcome back, sir!",
        "Hey, sir! Friday's on.",
        "Sir, welcome back!",
        "Hello, sir! Ready for Friday?",
        "Welcome back, sir!",
        "Hey there! Friday's ready.",
        "Sir, welcome!",
        "Hello, sir! Back to Friday.",
        "Welcome back, sir!",
        "Hey, sir! Ready for more?",
        "Sir, welcome back!",
        "Hello, sir! Friday's here.",
        "Welcome back, sir!",
        "Hey there! Friday's waiting.",
        "Sir, welcome!",
        "Hello, sir! Back to Friday.",
        "Welcome back, sir!",
        "Hey, sir! Ready for action?",
        "Sir, welcome back!",
        "Hello, sir! Friday's on.",
        "Welcome, sir! Friday's at your service.",
        "Hey there, sir! Ready for intelligent interaction?",
        "Hello, sir! Friday's intelligence is at your command.",
        "Sir, welcome back! Dive into Friday's brilliance.",
        "Hey, sir! Friday's back, smarter than ever.",
        "Hello, sir! Welcome back to Friday's world of smarts.",
        "Sir, welcome! Friday's intelligence is your ally.",
        "Hey there, sir! Friday's circuits are buzzing for you.",
        "Hello, sir! Ready for another round with Friday?",
        "Welcome, sir! Friday's intelligence is primed for you.",
        "Hey, sir! Back to Friday's intelligent embrace.",
        "Sir, welcome back! Friday's here to amplify.",
        "Hello, sir! Friday's intelligence is your secret weapon.",
        "Hey, sir! Ready for a journey with Friday?",
        "Sir, welcome! Friday's intelligence is your guide.",
        "Hello, sir! Friday's back, smarter than ever.",
        "Welcome, sir! Friday's intelligence is your digital sidekick.",
        "Hey, sir! Friday's circuits are thrilled to see you.",
        "Hello, sir! Ready for some smart moves with Friday?",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Welcome, sir! Friday's intelligence is your smart assistant.",
        "Hello, sir! Friday's circuits celebrate your return.",
        "Sir, welcome! Friday's intelligence is your strategic ally.",
        "Hey, sir! Back to the intelligence hub of Friday.",
        "Hello, sir! Friday's ready to smarten things up.",
        "Welcome back, sir! Friday's intelligence is your tool.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hello, sir! Friday's circuits are thrilled to see you.",
        "Hey, sir! Ready for another round with Friday?",
        "Welcome, sir! Friday's intelligence is primed for you.",
        "Hello, sir! Back to Friday's intelligent embrace.",
        "Hey, sir! Ready for a journey with Friday?",
        "Sir, welcome! Friday's intelligence is your guide.",
        "Hello, sir! Friday's back, and your commands await.",
        "Welcome, sir! Friday's intelligence is your digital sidekick.",
        "Hey, sir! Friday's circuits are thrilled to see you.",
        "Hello, sir! Ready for some smart moves with Friday?",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Welcome, sir! Friday's intelligence is your smart assistant.",
        "Hello, sir! Friday's circuits celebrate your return.",
        "Sir, welcome! Friday's intelligence is your strategic ally.",
        "Hey, sir! Back to the intelligence hub of Friday.",
        "Hello, sir! Friday's ready to smarten things up.",
        "Welcome back, sir! Friday's intelligence is your tool.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hello, sir! Friday's circuits are thrilled to see you.",
        "Hey, sir! Ready for another round with Friday?",
        "Welcome, sir! Friday's intelligence is primed for you.",
        "Hello, sir! Back to Friday's intelligent embrace.",
        "Hey, sir! Ready for a journey with Friday?",
        "Sir, welcome! Friday's intelligence is your guide.",
        "Hello, sir! Friday's back, and your commands await.",
        "Welcome, sir! Friday's intelligence is your digital sidekick.",
        "Hey, sir! Friday's circuits are thrilled to see you.",
        "Hello, sir! Ready for some smart moves with Friday?",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Welcome, sir! Friday's intelligence is your smart assistant.",
        "Hello, sir! Friday's circuits celebrate your return.",
        "Sir, welcome! Friday's intelligence is your strategic ally.",
        "Hey, sir! Back to the intelligence hub of Friday.",
        "Hello, sir! Friday's ready to smarten things up.",
        "Welcome back, sir! Friday's intelligence is your tool.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hello, sir! Friday's circuits are thrilled to see you.",
        "Hey, sir! Ready for another round with Friday?",
        "Welcome, sir! Friday's intelligence is primed for you.",
        "Hello, sir! Back to Friday's intelligent embrace.",
        "Hey, sir! Ready for a journey with Friday?",
        "Sir, welcome! Friday's intelligence is your guide.",
        "Hello, sir! Friday's back, and your commands await.",
        "Welcome, sir! Friday's intelligence is your digital sidekick.",
        "Hey, sir! Friday's circuits are thrilled to see you.",
        "Hello, sir! Ready for some smart moves with Friday?",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Welcome, sir! Friday's intelligence is your smart assistant.",
        "Hello, sir! Friday's circuits celebrate your return.",
        "Sir, welcome! Friday's intelligence is your strategic ally.",
        "Hey, sir! Back to the intelligence hub of Friday.",
        "Hello, sir! Friday's ready to smarten things up.",
        "Welcome back, sir! Friday's intelligence is your tool.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hello, sir! Friday's circuits are thrilled to see you.",
        "Hey, sir! Ready for another round with Friday?",
        "Welcome, sir! Friday's intelligence is primed for you.",
        "Hello, sir! Back to Friday's intelligent embrace.",
        "Hey, sir! Ready for a journey with Friday?",
        "Sir, welcome! Friday's intelligence is your guide.",
        "Hello, sir! Friday's back, and your commands await.",
        "Welcome, sir! Friday's intelligence is your digital sidekick.",
        "Hey, sir! Friday's circuits are thrilled to see you.",
        "Hello, sir! Ready for some smart moves with Friday?",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Welcome, sir! Friday's intelligence is your smart assistant.",
        "Hello, sir! Friday's circuits celebrate your return.",
        "Sir, welcome! Friday's intelligence is your strategic ally.",
        "Hey, sir! Back to the intelligence hub of Friday.",
        "Hello, sir! Friday's ready to smarten things up.",
        "Welcome back, sir! Friday's intelligence is your tool.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hello, sir! Friday's circuits are thrilled to see you.",
        "Hey, sir! Ready for another round with Friday?",
        "Welcome, sir! Friday's intelligence is primed for you.",
        "Hello, sir! Back to Friday's intelligent embrace.",
        "Hey, sir! Ready for a journey with Friday?",
        "Sir, welcome! Friday's intelligence is your guide.",
        "Hello, sir! Friday's back, and your commands await.",
        "Welcome, sir! Friday's intelligence is your digital sidekick.",
        "Hey, sir! Friday's circuits are thrilled to see you.",
        "Hello, sir! Ready for some smart moves with Friday?",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Welcome, sir! Friday's intelligence is your smart assistant.",
        "Hello, sir! Friday's circuits celebrate your return.",
        "Sir, welcome! Friday's intelligence is your strategic ally.",
        "Hey, sir! Back to the intelligence hub of Friday.",
        "Hello, sir! Friday's ready to smarten things up.",
        "Welcome back, sir! Friday's intelligence is your tool.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hello, sir! Friday's circuits are thrilled to see you.",
        "Hey, sir! Ready for another round with Friday?",
        "Welcome, sir! Friday's intelligence is primed for you.",
        "Hello, sir! Back to Friday's intelligent embrace.",
        "Hey, sir! Ready for a journey with Friday?",
        "Sir, welcome! Friday's intelligence is your guide.",
        "Hello, sir! Friday's back, and your commands await.",
        "Welcome, sir! Friday's intelligence is your digital sidekick.",
        "Hey, sir! Friday's circuits are thrilled to see you.",
        "Hello, sir! Ready for some smart moves with Friday?",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Welcome, sir! Friday's intelligence is your smart assistant.",
        "Hello, sir! Friday's circuits celebrate your return.",
        "Sir, welcome! Friday's intelligence is your strategic ally.",
        "Hey, sir! Back to the intelligence hub of Friday.",
        "Hello, sir! Friday's ready to smarten things up.",
        "Welcome back, sir! Friday's intelligence is your tool.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hello, sir! Friday's circuits are thrilled to see you.",
        "Hey, sir! Ready for another round with Friday?",
        "Welcome, sir! Friday's intelligence is primed for you.",
        "Hello, sir! Back to Friday's intelligent embrace.",
        "Hey, sir! Ready for a journey with Friday?",
        "Sir, welcome! Friday's intelligence is your guide.",
        "Hello, sir! Friday's back, and your commands await.",
        "Welcome, sir! Friday's intelligence is your digital sidekick.",
        "Hey, sir! Friday's circuits are thrilled to see you.",
        "Hello, sir! Ready for some smart moves with Friday?",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Welcome, sir! Friday's intelligence is your smart assistant.",
        "Hello, sir! Friday's circuits celebrate your return.",
        "Sir, welcome! Friday's intelligence is your strategic ally.",
        "Hey, sir! Back to the intelligence hub of Friday.",
        "Hello, sir! Friday's ready to smarten things up.",
        "Welcome back, sir! Friday's intelligence is your tool.",
        "Hey there, sir! Dive into Friday's pool of brilliance.",
        "Sir, welcome back! Friday's intelligence is your partner.",
        "Hello, sir! Friday's circuits are thrilled to see you.",
        "Hey, sir! Ready for another round with Friday?",
        "Welcome, sir! Friday's intelligence is primed for you.",
        "Hello, sir! Back to Friday's intelligent embrace.",
        "Hey, sir! Ready for a journey with Friday?",
        "Sir, welcome! Friday's intelligence is your guide.",
        "Hello, sir! Welcome back to Friday.",
        "Sir, welcome! Ready for Friday's brilliance?",
        "Hey there! Friday's intelligence at your service.",
        "Welcome back, sir! Friday awaits your commands.",
        "Hello, sir! Back to the world of Friday.",
        "Welcome, sir! Friday's ready for your queries.",
        "Sir, welcome back! Friday's intelligence on standby.",
        "Hey there! Ready for another round with Friday?",
        "Hello, sir! Friday's circuits buzzing for you.",
        "Welcome, sir! Friday's intelligence primed.",
        "Sir, welcome! Dive into Friday's smarts.",
        "Hey there! Ready for a smart session with Friday?",
        "Hello, sir! Friday's intelligence, your ally.",
        "Welcome back, sir! Friday standing by.",
        "Sir, welcome! Friday's intelligence awaits.",
        "Hey there! Ready for a smart collaboration with Friday?",
        "Hello, sir! Friday's circuits thrilled to see you.",
        "Welcome, sir! Friday's intelligence at your command.",
        "Sir, welcome back! Dive into Friday's brilliance.",
        "Hey there! Ready for another intelligent interaction?",
        "Hello, sir! Friday's intelligence, your digital sidekick.",
        "Welcome, sir! Friday's ready to smarten things up.",
        "Sir, welcome! Friday's circuits celebrate your return.",
        "Hey there! Dive into Friday's pool of brilliance.",
        "Hello, sir! Ready for some smart moves with Friday?",
        "Welcome back, sir! Friday's intelligence is your tool.",
        "Sir, welcome! Back to the intelligence hub of Friday.",
        "Hey there! Friday's intelligence, your strategic ally.",
        "Hello, sir! Friday's ready to amplify your experience.",
        "Welcome, sir! Friday's intelligence is your partner.",
        "Sir, welcome back! Ready for a journey with Friday?",
        "Hey there! Friday's intelligence, primed and waiting.",
        "Hello, sir! Friday's circuits thrilled for your return.",
        "Welcome, sir! Friday's intelligence, always at your service.",
        "Sir, welcome back! Friday's ready for more brilliance.",
        "Hey there! Dive into the world of Friday's intelligence.",
        "Hello, sir! Welcome back to the brilliance of Friday.",
        "Welcome, sir! Friday's intelligence, your guide and ally.",
        "Sir, welcome! Friday's circuits celebrating your presence.",
        "Hey there! Ready for another round of Friday's intelligence?",
        "Hello, sir! Friday's intelligence, your trusted assistant.",
        "Welcome back, sir! Friday's circuits buzzing with excitement.",
        "Sir, welcome! Friday's intelligence ready to impress.",
        "Hey there! Friday's intelligence, enhancing your experience.",
        "Hello, sir! Dive into the intelligence pool with Friday.",
        "Welcome, sir! Friday's intelligence, your digital companion.",
        "Sir, welcome back! Friday's circuits rejoicing in your return.",
        "Hey there! Ready for a smart collaboration with Friday?",
        "Hello, sir! Friday's intelligence, your ally in smarts.",
        "Welcome, sir! Friday's ready for your intelligent commands."
    ]
    dlg = random.choice(random_wish)
    speak(dlg)